CANTONS_OF_SWITZERLAND = {
    'ag': {'name': 'Aargau', 'uses_site': False},
    'ai': {'name': 'Appenzell Innerrhoden', 'uses_site': False},
    'ar': {'name': 'Appenzell Ausserrhoden', 'uses_site': False},
    'be': {'name': 'Bern', 'uses_site': False},
    'bl': {'name': 'Basel-Landschaft', 'uses_site': False},
    'bs': {'name': 'Basel-Stadt', 'uses_site': False},
    'fr': {'name': 'Fribourg', 'uses_site': False},
    'ge': {'name': 'Genève', 'uses_site': False},
    'gl': {'name': 'Glarus', 'uses_site': False},
    'gr': {'name': 'Graubünden', 'uses_site': False},
    'ju': {'name': 'Jura', 'uses_site': False},
    'lu': {'name': 'Luzern', 'uses_site': False},
    'ne': {'name': 'Neuchâtel', 'uses_site': False},
    'nw': {'name': 'Nidwalden', 'uses_site': False},
    'ow': {'name': 'Obwalden', 'uses_site': False},
    'sg': {'name': 'St. Gallen', 'uses_site': False},
    'sh': {'name': 'Schaffhausen', 'uses_site': False},
    'so': {'name': 'Solothurn', 'uses_site': False},
    'sz': {'name': 'Schwyz', 'uses_site': False},
    'tg': {'name': 'Thurgau', 'uses_site': False},
    'ti': {'name': 'Ticino', 'uses_site': False},
    'ur': {'name': 'Uri', 'uses_site': False},
    'vd': {'name': 'Vaud', 'uses_site': False},
    'vs': {'name': 'Valais', 'uses_site': False},
    'zg': {'name': 'Zug', 'uses_site': False},
    'zh': {'name': 'Zürich', 'uses_site': False}
}